src/commands/lottery.js, src/index.js, src/utils/json/messages.json
closes #27 
Esse PR adiciona a acumulação do prêmio da loteria caso ninguém tenha comprado tickets, fazendo com que a próxima loteria valha mais
=> acumula a loteria se ninguém ganhar

src/commands/inventory.js, src/commands/item.js, src/events/interactions.js, src/schemas/user-schema.js, src/utils/functions.js, src/utils/json/messages.json
closes #28 
Adiciona 4 tipos diferentes de ordenação do inventário, que o usuário pode escolher entre elas
- Adiciona um novo campo inventorySort na schema do usuário
- Adiciona um novo botão ao ver o inventário que te permite mudar o tipo de ordenação
- 4 tipos de ordenação: valor do item, valor total, quantidade e alfabético
- adiciona .toLowerCase() direto no getItem(), remove dos outros lugares
=> feat: add inventory sorting

src/commands/explore.js, src/commands/fish.js, src/commands/hunt.js, src/commands/inventory.js, src/commands/mine.js
conserta um erro onde o bot assumia que sua locale era pt-BR ou en-US para buscar o nome dos itens
- Em todos os lugares que existia uma expressão do tipo items[item][interaction.locale], foi adicionado um ?? items[item]['en-US'], que garante que um nome sempre será retornado
=> Busca o nome dos itens corretamente

src/commands/explore.js, src/commands/fish.js, src/commands/hunt.js, src/commands/inventory.js, src/commands/item.js, src/commands/mine.js, src/schemas/user-schema.js, src/utils/json/items.json, src/utils/json/messages.json
Adiciona um novo subcomando `use` para o comando `inventory`
- Cria o `/inventory use`
- Adiciona um novo texto usável se um item puder ser usado no `/iteminfo`
- Adiciona o primeiro item usável, a mochila adiciona 200.000 falcoins no limite de inventário
- adiciona um novo campo a schema do usuário inventoryBonus
=> Cria o inventory use

src/commands/inventory.js, src/utils/json/messages.json
fixes #36 
Garante que as opções do menu de seleção do inventory craft serão entre 1 e 25
- Se o usuário puder construir mais de 25 items, cortamos pra 25
- Se ele não pode construir nenhum item, mandamos uma mensagem falando isso
=> fix: inventory craft select menu limit

src/commands/inventory.js, src/commands/item.js, src/commands/leaderboard.js
closes #35 
Adds autocomplete for item throughout all commands
- Add autocomplete in leaderboard items
- Add autocomplete in iteminfo 
- Add autocomplete in various inventory subcommands, with the items relevants to it
=> feat: create autocomplete for items

src/commands/inventory.js, src/commands/item.js, src/utils/json/items.json, src/utils/json/messages.json
This pr adds 3 new items, and one of them is a mytical one, which is a new type of item
- New item fishwich
- New item clover
- New item snowflake
- The eternal snowflake is the first of a new kind of items that are the mythical ones, the can't be sold but have really grate effects
- Adds a message saying all usable items and their effects if you don't pass a item in /inventory use
=> feat: new items and new rarity

package-lock.json, src/commands/leaderboard.js
Closes #62 
This pr fixes the leaderboard item sort error and also change the package-lock version to 2.9.2.
=> fix: leaderboard item sort error and package-lock version

src/index.js
This PR fixes the inventory worth calculation when there is a Eternal Snowflake in the player's inventory
=> fix: inventory worth calculation

src/commands/inventory.js
fixes #67 
This PR fixes the bug that made eternal snowflake show up in the `/inventory sell` autocomplete
- Refactored the code for the inventory autocomplete, making the conditions more dynamic and easier to read
- Also fixed the inventory calc, making the cost be the sum of the ingredients cost if the item is craftable, or the item value if it's not
=> feat: improve inventory autocomplete

src/commands/explore.js, src/commands/fish.js, src/commands/hunt.js, src/commands/inventory.js, src/commands/mine.js, src/commands/stats.js, src/commands/vote.js, src/commands/work.js, src/events/interactions.js, src/schemas/user-schema.js, src/utils/json/messages.json
closes #64 
This PR adds a user statistics system, with 10 initial statistics that are tracked globally
- stats command that shows the stats
- new stats map in user document
- 10 initial stats
=> feat: create user stats system

src/bot.js, src/commands/economy/scratch.js, src/commands/economy/stats.js, src/schemas/user-schema.js, src/utils/json/messages.json
Creates two new statistics, one that tracks earnings from lottery and one that tracks jackpots from scratch
=> feat: create lotteryWins and scratchJackpots stats

src/commands/economy/leaderboard.js
fixes #97 
Fixes the bug where the item emoji was missing from the leaderboard description
- Used the new getItemName function in embed description when is a item leaderboard
=> fix: leaderboard item description missing emoji

src/commands/economy/explore.js, src/commands/economy/fish.js, src/commands/economy/hunt.js, src/commands/economy/mine.js, src/utils/functions.js
fixes #92 
Improve gathering item commands luck when the random events are active
- Change pick function to have a luck argument that impacts the pick weight
- Make fish, hunt, explore and mine commands have improved luck when their respective random events are active
=> feat: improve commands luck when events are active

src/bot.js, src/commands/economy/farm.js, src/commands/economy/item.js, src/commands/utility/help.js, src/schemas/user-schema.js, src/utils/json/items.json, src/utils/json/levels.json, src/utils/json/messages.json
> Closes #65
Adds a farming system to Falbot, users can plant seeds in their plots, as well as water, harvest, and uproot. When grown, the user can harvest them and earn a random amount of each type of crop planted.
- `/farm view`: show user's farm
- `/farm plant`: plant a crop
- `/farm harvest`: harvest all available crops
- `/farm water`: water all crops
- `/farm uproot`: uproot a specified plot
|:--:| 
| `/farm view` |
| `/farm plant crop: 🍀 Clover` |
| `/farm water` |
| `/farm harvest` |
| `/farm uproot` |
and much more!
=> Create a farming system

src/commands/economy/fight.js, src/commands/economy/horseduel.js, src/commands/economy/russianroulette.js, src/utils/json/messages.json
> Closes #82 
Allow owner of a competitive command (horseduel, russianroulette or fight) to cancel it.
**Bonus feature:** horseduel and russianroulette now have a realtime countdown.
=> Cancel competitive command

src/commands/economy/vote.js, src/schemas/user-schema.js, src/utils/functions.js, src/utils/json/messages.json
This pr makes premium users receive 2x falcoins when voting, premium users are any users that signed up to falbot's patreon
- Changes userSchema to have a premium section
- Creates a checkIfUserIsPremium function
- Creates vote premium bonus logic
=> feat: premium users receive 2x falcoins on vote command

package-lock.json, package.json, src/bot.js, src/commands/fun/games.js, src/utils/json/messages.json
Update falgames to v1.2.0 and add the remaining minigames, since now falbot can read message contents
- Add would you rather
- Add trivia
- Add fast type
- Add guess the pokemon
- Add hangman
- Add rock paper scissors
- Add wordle
=> feat: add the remaining falgames minigames

src/commands/economy/inventory.js, src/commands/economy/market.js, src/database/market.js, src/schemas/market-schema.js, src/utils/functions.js, src/utils/json/messages.json
- **feat: improve paginate function**
- **feat: boost up market and inventory sellall commands**
closes #124 
Turbos up market and inventory sellall commands to work better
- Adds market history
- Adds qol texts to /inventory sellall
- Makes /inventory sellall consider market orders
- Adds a select menu for each page in /market all
- Improves paginate function to paginate components as well
- Improves market schema
=> feat: turbo market and inventory sellall commands

src/bot.js, src/commands/economy/leaderboard.js
This PR makes the server leaderboards much faster, but it uses the server members intent, so i need to wait for discord to approve it
- we get a list of members in the server and make mongo do the heavy work
- we also use the list of member to get the name to put in the leaderboard
- removed the getMember function
=> feat: faster leaderboards

src/utils/functions.js
This is a pretty simple PR that makes the code from the format function much better, actually using the fact that falcoins are already a number and using the function .toLocaleString() to format it
=> refactor: format function to toLocaleString

package-lock.json, package.json, src/bot.js, src/commands/economy/bank.js, src/commands/economy/blackjack.js, src/commands/economy/crash.js, src/commands/economy/donate.js, src/commands/economy/exchange.js, src/commands/economy/fight.js, src/commands/economy/horse.js, src/commands/economy/horseduel.js, src/commands/economy/inventory.js, src/commands/economy/lottery.js, src/commands/economy/market.js, src/commands/economy/roulette.js, src/commands/economy/russianroulette.js, src/commands/economy/slot.js, src/commands/economy/snakeeyes.js, src/commands/economy/vote.js, src/handlers/commandHandler.js, src/handlers/databaseHandler.js, src/index.js, src/utils/functions.js
update a lot of dependencies
- update, eslint, prettier, discord.js and others
- removes dotenv
=> chore: update dependencies

src/commands/economy/market.js, src/database/market.js, src/schemas/market.js
Fixes some issues in market history, like sometimes saying that 0 items were sold or messages havind different language
- Fixes a bug where sometimes it would say that 0 items were bought
- Changes market history schema to just be an array insteado of an array of string
- Fixes a bug where messages in market history could be different languages, because we saved strings, now we save objects
=> fix: market history
