falcao-g/Falbot

src/commands/contextProfile.js

adiciona o comando perfil como context menu

---

src/commands/inventory.js
src/utils/json/items.json
src/utils/json/messages.json

mandar lista de itens equipaveis no /inventory equip

---

src/events/interactions.js
src/utils/functions.js

quando um cooldown acabava, o código colocava aquele cooldown como 0 e apagava todos os outros registros, isso foi consertado

novo sistema de cooldown consertado

---

src/commands/inventory.js
src/events/interactions.js
src/utils/json/items.json
src/utils/json/messages.json

menu com itens craftaveis adicionado

---

src/commands/inventory.js
src/events/interactions.js
src/utils/json/messages.json

botões de craftar 1, 10, 100 e máximo que aparecerem depois de vc ter construido alguma coisa

criado botões no craft

---

src/commands/item.js
src/events/interactions.js

cria botões para ver o item anterior/posterior

---

src/utils/json/items.json

conserta alguns itens e suas propriedades

---

src/commands/ranks.js
src/utils/json/levels.json
src/utils/json/messages.json

Este PR, adiciona 3 novos ranks para o bot e adiciona paginação para o /ranks todos, cada embed mostra até 20 ranks

3 novos ranks e paginação adicionada

---

src/commands/horseduel.js
src/commands/russianroulette.js
src/utils/functions.js

Agora o criador da corrida/roleta tem um botão que o permite iniciar os jogos antes do timer de 1 minutos.

Adicionado botão para iniciar a corrida e roleta russa (falcao-g#23)

---

src/commands/horseduel.js
src/commands/russianroulette.js

Esse PR conserta o bug de "farmar" vitórias, simplemeste adicionando um if que analisa se tinha mais de um usuário quando a competição começou

conserta o bug de farmar vitorias

---

src/commands/channel.js
src/commands/command.js
src/events/interactions.js
src/index.js
src/schemas/guilds-schema.js
src/utils/json/messages.json

closes #21 
Este PR adiciona um sistema de desativar comandos, administradores podem desativar comandos em seus servidores, o bot não responderá mais aquele comando naquele servidor específico, qualquer comando desativado pode ser reativado a qualquer momento

Adiciona opção para administradores desativarem comandos

---

src/commands/leaderboard.js
src/utils/json/messages.json

Este PR refatora o código das leaderboards, fazendo elas ficarem mais versáteis e com menos linhas, assim fica mais simples de adicionar novos tipos no futuro, falando de novos tipos, também adicionei uma leaderboard por item, agora o usuário pode ver o rank de jogadores com o maior número de determinado item

Refatora as leaderboards e adiciona por itens

---

src/utils/json/items.json

closes #37 
Ajusta o valor dos itens, colocando uma margem de pelo menos 10% do valor de seus ingredientes

ajusta o valor dos itens

---

.github/ISSUE_TEMPLATE/bug_report.yml
.github/ISSUE_TEMPLATE/config.yml
.github/ISSUE_TEMPLATE/feature_request.yml
.github/pull_request_template.md

Adiciona template para issues e prs, assim estes terão um padrão entre si

Adiciona template para issues e prs

---

.gitignore
.husky/pre-commit
.prettierignore
.prettierrc
.vscode/extensions.json
.vscode/settings.json
package-lock.json
package.json

Este pr cria ações pre-commit, assim toda vez que um commit é realizado, o eslint e o prettier são executados nos arquivos modificados
- adiciona configuração do prettier
- adiciona lint-staged e husky
- adiciona ação pre-commit
- remove os arquivos de configuração do .vscode

Cria configuração pre-commit

---

.eslintrc
.prettierrc
src/commands/help.js
src/commands/inventory.js
src/commands/item.js
src/commands/reminder.js
src/events/interactions.js

This pr cleans up a lot of unnecessary code in the interactions event
- Establishes that customId's will follow the <command> <subcommand> <args> format for all button interactions
- Makes all string select menus customId's follow the <command> <subcommand> format

feat: clean up interactions event

---

src/commands/leaderboard.js
src/utils/json/messages.json

This PR adds a new type of leaderboard, ranked by daily votes

feat: create leaderboard vote

---

CONTRIBUTING.md

This PR fixes translation errors on the CONTRIBUTING.md
Changed text on CONTRIBUTING.md file, some texts that were in Portuguese were translated into English.

docs: text translated into default language

---

.env.example

Closes #54 
<br>
Added `.env.example` file with content.
The content of `.env.example` are :
`TOKEN="dicord-bot-token"`
`MONGODB_URI="mongodb-uri"`
`Authorization="topgg-core-authorization"`

Add `.env.example` file

---

CODE_OF_CONDUCT.md
CONTRIBUTING.md
README.md

Creates the Code of Conduct 
- Create the Code of Conduct
- Refactor the Self Host Warnings

docs: create code of conduct

---

src/commands/horse.js
src/commands/ranks.js
src/commands/slot.js

Fixes /ranks rankup not responding when you use the command, despite actually increasing your rank

fix: commands importations problems

---

src/commands/cooldowns.js
src/commands/explore.js
src/commands/fish.js
src/commands/hunt.js
src/commands/mine.js
src/commands/work.js
src/index.js
src/utils/json/messages.json

closes #66 
Creates a random events system, these events happen randomly and give various effects to all players
- Created the base of the system
- Each 45 minutes the bot tries to start a event, if that event is already active, it doesn't activate it again
- 5 events for now

feat: create random events system

---

src/commands/economy/horse.js
src/commands/economy/profile.js
src/commands/economy/tictactoe.js
src/commands/economy/work.js
src/utils/json/items.json
src/utils/json/messages.json

Creates a new coffeebean and coffee item
- Adds a coffeebean item
- Adds a coffee item made with 40 coffebean's, this gives 2x more falcoins when working

Feat: add coffe item

---

src/commands/economy/bank.js
src/commands/economy/blackjack.js
src/commands/economy/crash.js
src/commands/economy/donate.js
src/commands/economy/exchange.js
src/commands/economy/fight.js
src/commands/economy/horse.js
src/commands/economy/horseduel.js
src/commands/economy/inventory.js
src/commands/economy/lottery.js
src/commands/economy/roulette.js
src/commands/economy/russianroulette.js
src/commands/economy/scratch.js
src/commands/economy/slot.js
src/commands/economy/snakeeyes.js
src/commands/economy/tictactoe.js
src/utils/functions.js

- Improves specialArg making it compare to any numerical value
- Uses specialArg in various places that were not possible before

feat: improve specialArg funcionality

---

src/bot.js
src/commands/economy/inventory.js

- Makes item autocomplete correctly return items ignoring their emojis
- Also makes the item autocomplete return using the emoji if a emoji is inputted

feat: improve item autocomplete

---

src/commands/economy/scratch.js

Debuffs scratch, making it less likely to give money, also making the percentages more obvious

chore: debuff scratch

---

src/commands/economy/inventory.js

Fix `/inventory sellall` responding to buttons of other commands

fix: inventory sellall responding to other buttons

---

.env.example
package-lock.json
src/commands/economy/roulette.js

fix: rollete message

---

src/commands/economy/work.js

Fixes a importation problem in /work

fix: work missing function importation

---

src/commands/economy/vote.js

fixes #98 
Fixes the vote bonus text percentage, capping it at 150% as intended

fix: vote bonus text percentage

---

.all-contributorsrc
README.md

Adds all contributors bot into the repository

docs: add all contributors bot

---

package-lock.json
package.json
src/commands/economy/tictactoe.js
src/commands/fun/roll.js
src/commands/fun/snake.js
src/utils/json/messages.json

This pr removes falbot-roll, falbot-snake and tictactoe-board and implements falgames instead of them
- Makes roll use falgames
- Makes snake use falgames
- Makes tictactoe use falgames

feat: integrate falgames

---

src/commands/economy/item.js
src/commands/economy/leaderboard.js

fixes #99 
Fixes autocomplete in leaderboard item and iteminfo

fix: autocomplete in leaderboard and iteminfo

---

src/bot.js
src/commands/economy/market.js
src/commands/fun/connect4.js
src/commands/fun/findemoji.js
src/commands/fun/flood.js
src/commands/fun/matchpairs.js
src/commands/fun/mineswepper.js
src/commands/fun/tictactoe.js
src/utils/json/messages.json

Adds more games from the falgames package
- Adds Minesweeper
- Adds flood
- Adds find emoji
- Adds match pairs

feat: add more games from falgames

---

package-lock.json
package.json
src/commands/fun/games.js
src/commands/fun/roll.js
src/utils/json/messages.json

Update falgames to v1.0.2
- Update falgames package
- Change embed color for all falgames games to member.displayColor
- Remove comment from roll because now the properties actually exist
- Increase roll limit
- Put snake option - scoreText - in the right place

update falgames package

---

package-lock.json
package.json
src/commands/fun/games.js

this pr adds the 2048 game from falgames
- Adds a 2048 subcommand to the /games command
- Updates falgames to v1.1.1

feat: add 2048 game

---

.eslintrc
.gitignore
src/bot.js
src/commands/economy/contextProfile.js
src/commands/economy/explore.js
src/commands/economy/farm.js
src/commands/economy/fish.js
src/commands/economy/hunt.js
src/commands/economy/inventory.js
src/commands/economy/item.js
src/commands/economy/leaderboard.js
src/commands/economy/market.js
src/commands/economy/mine.js
src/commands/economy/ranks.js
src/commands/economy/vote.js
src/commands/economy/work.js
src/index.js
src/utils/functions.js

Change project eslint and gitignore rules
- Adds .DS_Store to gitignore
- Add max-params, prefer-destructuring and no-console rules
- Removes no-alert rule

chore: change project rules

---

src/commands/economy/farm.js

General changes and fixes for farm command
- adds try/catch
- make uproot not break bot if player has no crops planted
- watering cooldown indicator vanishes when you can water the crops

general changes for farm command

---

src/commands/economy/fight.js
src/commands/economy/lottery.js

- Caps self damage in fight to 20
- Each attack has a different chance
- Fixes lottery

Improve fight command and fix lottery

---

src/bot.js
src/commands/economy/explore.js
src/commands/economy/farm.js
src/commands/economy/fish.js
src/commands/economy/hunt.js
src/commands/economy/inventory.js
src/commands/economy/market.js
src/commands/economy/mine.js
src/commands/economy/scratch.js
src/commands/economy/stats.js
src/commands/economy/vote.js
src/commands/economy/work.js
src/events/interactions.js
src/schemas/user-schema.js
src/utils/json/messages.json

Improves the stats system and includes 3 new ones
- Makes so that new stats don't break the default values
- Adds timesWatered, cropsHarvested and listingsSold

feat: improve stats system along with 3 new others

---

src/commands/economy/fight.js
src/utils/json/messages.json

Fights now create a thread to isolate each message sent.
- Changed fight.js
- Added FIGHT_ACCEPTED message in messages.json

feat: create a new thread for each fight

---

src/commands/economy/fight.js
src/utils/json/messages.json

This reverts commit the pr that creates a thread for each fight because of some issues

Revert "feat: create a new thread for each fight (#145)"

---

.github/ISSUE_TEMPLATE/bug_report.yml
.github/ISSUE_TEMPLATE/config.yml
.github/ISSUE_TEMPLATE/feature_request.yml
.github/pull_request_template.md

Improve templates for issue and pr
- Improves bug issue template
- Improves feature request issue template
- Improves pull request template

docs: improved templates

---

src/utils/json/levels.json
src/utils/json/messages.json

Adds 3 new ranks
- Adds rank Duke
- Adds rank Prince
- Adds rank Archon

feat: add 3 new ranks

---

src/utils/json/items.json

Fixed some harvest amounts so it becomes more balanced
- weeds: 5-20x
- wheat: 15-40x

fix: tweak some harvest amounts

---

src/commands/economy/farm.js
src/commands/economy/inventory.js

Adds more numerize to commands to improve QOL for users
- Numerize in inventory craft
- Numerize in farm plant

feat: more numerize

---

src/commands/economy/market.js

Fix market listings in market view not being added together, also fixes item names in market history not changing based on language

fix: market listings not added together

---

src/commands/fun/coinflip.js

Changes the name of the /coinflip command to "caraoucoroa" in pt-BR

refactor: girarmoeda -> caraoucoroa
